spring:
  application:
    name: service01

server:
  port: 8181

spring:
  thymeleaf:
    cache: false

###
#   Database Settings
###
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demotra?verifyServerCertificate=false&useSSL=false&requireSSL=false
    platform: mysql
    username: demotra
    password: demotra
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false # true
        use_sql_comments: true
        format_sql: true